version: '3.9'

services:
  spring_db:
    image: postgres:${POSTGRES_VERSION:-16.1}
    container_name: spring_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    networks:
      - spring_network
    volumes:
      - spring_db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env

volumes:
  spring_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  spring_network:
    driver: bridge